### ISSUE TITLE
this works well only for small subset of effects for monads like rx observable

### ISSUE THREAD

**Issue by awto** [pelotom/burrido#1]
Here is a pretty typical and simple example, say, we need to update DB before some further actions, this is HTTP POST running using promises. Promises may be turned into observable, and JS has no its own side effects:

```
doMerge(function*() {
  const m = yield fromPromise(updateDb())
  const x = yield from([1,2])
  return `${x} ${m}`
}).subscribe(function(res) {
  console.log(res)
})
```

This updates DB 4 times!

More details in [this gist](https://gist.github.com/awto/9f5337fcf205df335c92f93a859e2fdf).
And it is even theoretically not possible, arbitrary monad requires first class continuations, just coroutines are not enough.

There is in fact my tools (sorry for promoting it in this issue, but I suppose it may be interesting) may use same generators syntax for arbitrary monad.

**Comment by pelotom** [comment]
Hi, thanks for the note! Yes, the fact that the generator block cannot have side-effects is a known limitation due to not having cloneable or immutable generators, which I note [in the library I'm using to simulate them](https://github.com/pelotom/immutagen#emulated-immutability).

You can however always accomplish what you want in practice by choosing an appropriate monad to wrap the effects. For example, if we instead use a `Monad` for _lazy_ `Observable`s:

``` javascript
const { Do: doMerge } = Monad({
  pure: x => () => just(x),
  bind: (m, f) => () => m().flatMap(x => f(x)())
})
```

and rewrite your code as

``` javascript
doMerge(function*() {
  const m = yield () => fromPromise(updateDb())
  const x = yield () => from([1,2])
  return `${x} ${m}`
})().subscribe(function(res) {
  console.log(res)
})
```

then everything works as expected with no repetition of side-effects. This is obviously not ideal; it would be nice if we could deal directly with `Observable`s... this library is really a proof of concept to demonstrate that it would be really useful if JS generators could get a `clone` method. I will update the example in the `README` to reflect this.

Thanks for the link to your project, it looks quite interesting. Transpilation may indeed be the best practical approach at the moment, given the above limitations. Cheers!

**Comment by awto** [comment]
I see, clone would change everything, any monad could be possible to represent, there is a paper about this if interesting [Representing Monad](http://citeseerx.ist.psu.edu/viewdoc/summary?doi=10.1.1.43.8213)

**Comment by pelotom** [comment]
The link to the paper you gave seems to be broken...

**Comment by awto** [comment]
now it seems to work, some citeseerx issue I suppose
